version: "3.9"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      MONGO_URL: mongodb://admin:admin@mongo:27017
    volumes:
      - .:/code
    depends_on:
      - mongo
    ports:
      - 5000:5000
